// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI commands (migrate, studio) need a direct, non-pooled connection.
  // The app itself connects via the pooled DATABASE_URL (see src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
